### ISSUE TITLE
Removes portainer stack environement variables.

### ISSUE THREAD

**Issue by ariselseng** [docker-how-to/portainer-bash-scripts#2]
I tested now the code and it removed the current environment variables.

Instead of sending Env: [] it could first GET a stack with current data, and use that json as a starting point and adding the stack file on "top of it". So that any additional stuff portainer uses does not get overwritten.

**Comment by itamarjp** [comment]
I need a feature to load .env from a file and pass it to  Env: []

**Comment by ariselseng** [comment]
You should probably create a separate issue for that. If my PR gets in, then it will be relatively easy to add this.
